// Generated by CoffeeScript 1.6.3
(function() {
  var ActionController, assert, classkit;

  assert = require('assert');

  classkit = require('coffee_classkit');

  ActionController = require('../action_controller');

  describe('ActionController', function() {});

}).call(this);
