// Generated by CoffeeScript 1.6.3
(function() {
  var Costa, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Costa = (function(_super) {
    __extends(Costa, _super);

    function Costa() {
      _ref = Costa.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Costa.extendsWithProto();

    Costa.module = module;

    Object.defineProperty(Costa, 'root', {
      get: function() {
        var _ref1;
        return (_ref1 = this.application) != null ? _ref1.root : void 0;
      }
    });

    Costa.require = function() {
      var _ref1;
      return (_ref1 = this.application) != null ? _ref1.require.apply(_ref1, arguments) : void 0;
    };

    return Costa;

  })(require('coffee_classkit').Module);

}).call(this);
