// Generated by CoffeeScript 1.6.3
(function() {
  var Connect, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Connect = (function(_super) {
    __extends(Connect, _super);

    function Connect() {
      _ref = Connect.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Connect.extendsWithProto().concern();

    Connect.ClassMethods = (function() {
      function ClassMethods() {}

      ClassMethods.prototype.connectMiddleware = function(middleware) {
        return function(callback) {
          return middleware(this.req, this.res, function(err) {
            return callback(err);
          });
        };
      };

      return ClassMethods;

    })();

    return Connect;

  })(require('coffee_classkit').Module);

}).call(this);
