// Generated by CoffeeScript 1.6.3
(function() {
  var ActionController, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = ActionController = (function(_super) {
    __extends(ActionController, _super);

    function ActionController() {
      _ref = ActionController.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    ActionController.extendsWithProto();

    ActionController.includeAll(module, {
      prefix: './'
    }, 'connect', 'callbacks');

    ActionController.abstract = true;

    return ActionController;

  })(require('./request_controller'));

}).call(this);
