// Generated by CoffeeScript 1.6.3
(function() {
  var SocketController,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = SocketController = (function(_super) {
    __extends(SocketController, _super);

    SocketController.extendsWithProto();

    SocketController.includeAll(module, {
      prefix: './'
    }, 'callbacks');

    SocketController.abstract = true;

    SocketController.bind = function(sockets) {
      var _this = this;
      sockets.on('connection', function(socket) {
        _this.bindActions(socket);
        return _this.dispatch(socket, 'connect');
      });
      return this;
    };

    SocketController.bindActions = function(socket, actions) {
      var _this = this;
      if (actions == null) {
        actions = this.actionMethods;
      }
      actions.forEach(function(action) {
        return socket.on(action, function() {
          return _this.dispatch(socket, action);
        });
      });
      return this;
    };

    SocketController.dispatch = function(socket, action) {
      return new this(socket).proccess(action);
    };

    function SocketController(socket) {
      this.socket = socket;
    }

    return SocketController;

  })(require('./abstract_controller'));

}).call(this);
