// Generated by CoffeeScript 1.6.3
(function() {
  var Application, Costa, classkit, express,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  classkit = require('coffee_classkit');

  express = require('express');

  Costa = require('../');

  module.exports = Application = (function(_super) {
    __extends(Application, _super);

    classkit.inject(Application);

    Application.includeAll(module, {
      prefix: './application'
    }, 'initialization');

    Application.express = express;

    function Application(_arg) {
      var self;
      this.root = (_arg != null ? _arg : {}).root;
      self = this.constructor.express();
      self.constructor = this.constructor;
      self.__proto__ = this.__proto__;
      self.root = this.root;
      return self;
    }

    return Application;

  })(Function);

}).call(this);
