// Generated by CoffeeScript 1.6.3
(function() {
  module.exports = function(programm, context) {
    var app, key, repl, type, val, _i, _len, _ref, _ref1;
    if (context == null) {
      context = {};
    }
    type = programm.interactive === true ? 'coffee' : programm.interactive;
    programm.repl = repl = ((function() {
      switch (type) {
        case 'node':
          return require('repl');
        default:
          return require('coffee-script/lib/coffee-script/repl');
      }
    })()).start({
      prompt: "eve@" + type + "> "
    }).on('exit', function() {
      return process.exit();
    });
    repl.context.programm = programm;
    for (key in context) {
      val = context[key];
      repl.context[key] = val;
    }
    if (app = context.app) {
      _ref = ['models', 'controllers'];
      for (_i = 0, _len = _ref.length; _i < _len; _i++) {
        type = _ref[_i];
        _ref1 = app[type];
        for (key in _ref1) {
          val = _ref1[key];
          repl.context[key] = val;
        }
      }
      if (programm.sync) {
        require('./repl_sync')(app, repl);
      }
    }
    if (process.env.HOME) {
      try {
        return require('repl.history')(repl, "" + process.env.HOME + "/.node_history");
      } catch (_error) {}
    }
  };

}).call(this);
