// Generated by CoffeeScript 1.6.3
(function() {
  var Errors,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Errors = (function(_super) {
    __extends(Errors, _super);

    Errors.extendsWithProto();

    function Errors() {
      this.messages = {};
    }

    Errors.prototype.clear = function() {
      this.messages = {};
      return this;
    };

    Errors.prototype.has = function(field) {
      var _ref;
      return (_ref = this.messages[field]) != null ? _ref.length : void 0;
    };

    Errors.prototype.hasAny = function() {
      var error;
      for (error in this.messages) {
        return true;
      }
      return false;
    };

    Errors.prototype.first = function() {
      var error;
      for (error in this.messages) {
        if (this.messages[error].length) {
          return this.messages[error][0];
        }
      }
      return false;
    };

    Errors.prototype.add = function(field, message) {
      var _base, _ref;
      if (!message) {
        _ref = ['base', field], field = _ref[0], message = _ref[1];
      }
      ((_base = this.messages)[field] || (_base[field] = [])).push(message);
      return this;
    };

    return Errors;

  })(require('coffee_classkit').Module);

}).call(this);
