// Generated by CoffeeScript 1.6.3
(function() {
  var PersistedValidations, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = PersistedValidations = (function(_super) {
    __extends(PersistedValidations, _super);

    function PersistedValidations() {
      _ref = PersistedValidations.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    PersistedValidations.extendsWithProto().concern();

    PersistedValidations.includedBlock = function() {
      return this.aliasMethodChain('save', 'validations');
    };

    PersistedValidations.ClassMethods = (function() {
      function ClassMethods() {}

      return ClassMethods;

    })();

    PersistedValidations.prototype.saveWithValidations = function(callback) {
      return this.runValidations(function(err, isValid) {
        if (err) {
          return typeof callback === "function" ? callback(err) : void 0;
        }
        if (!isValid) {
          return typeof callback === "function" ? callback('Record invalid') : void 0;
        }
        return this.saveWithoutValidations(callback);
      });
    };

    return PersistedValidations;

  })(require('coffee_classkit').Module);

}).call(this);
