// Generated by CoffeeScript 1.6.3
(function() {
  var Args, SecondaryIndexes, lingo, _, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  _ = require('underscore');

  lingo = require('lingo');

  Args = require('../support/args');

  module.exports = SecondaryIndexes = (function(_super) {
    __extends(SecondaryIndexes, _super);

    function SecondaryIndexes() {
      _ref = SecondaryIndexes.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    SecondaryIndexes.extendsWithProto().concern();

    SecondaryIndexes.includedBlock = function() {};

    SecondaryIndexes.ClassMethods = (function() {
      function ClassMethods() {}

      ClassMethods.prototype.secondaryIndex = function() {
        var fields, options, _ref1,
          _this = this;
        _ref1 = Args.findOptions(arguments), options = _ref1[0], fields = _ref1[1];
        return fields.forEach(function(field) {
          _this[lingo.camelcase('getBy', field)] = function(value, callback) {};
          return _this[lingo.camelcase('findBy', field)] = function() {};
        });
      };

      return ClassMethods;

    })();

    return SecondaryIndexes;

  })(require('coffee_classkit').Module);

}).call(this);
