// Generated by CoffeeScript 1.6.3
(function() {
  var Confirmation, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Confirmation = (function(_super) {
    __extends(Confirmation, _super);

    function Confirmation() {
      _ref = Confirmation.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Confirmation.extendsWithProto().concern();

    Confirmation.ClassMethods = (function() {
      function ClassMethods() {}

      ClassMethods.prototype.validatesConfirmationOf = function() {
        return this.validatesEachSync(arguments, function(field, options) {
          var value, value_confirm;
          value = this[field];
          if (options.allowNull && (value == null)) {
            return;
          }
          if (options.allowBlank && !value) {
            return;
          }
          if ((value_confirm = this["" + field + "_confirmation"]) != null) {
            if (value_confirm !== value) {
              return this.errors.add(field, 'Confirmation does not match');
            }
          } else {
            return this.errors.add(field, 'No confirmation');
          }
        });
      };

      return ClassMethods;

    })();

    return Confirmation;

  })(require('coffee_classkit').Module);

}).call(this);
