// Generated by CoffeeScript 1.6.3
(function() {
  var Presence, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Presence = (function(_super) {
    __extends(Presence, _super);

    function Presence() {
      _ref = Presence.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Presence.extendsWithProto().concern();

    Presence.ClassMethods = (function() {
      function ClassMethods() {}

      ClassMethods.prototype.validatesPresenceOf = function() {
        return this.validatesEachSync(arguments, function(field, options) {
          var value;
          value = this[field];
          if (!(value || (value != null) && options.allowBlank)) {
            return this.errors.add(field, options.message || 'Should be present');
          }
        });
      };

      return ClassMethods;

    })();

    return Presence;

  })(require('coffee_classkit').Module);

}).call(this);
