// Generated by CoffeeScript 1.6.3
(function() {
  var Uniquiness, _ref,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  module.exports = Uniquiness = (function(_super) {
    __extends(Uniquiness, _super);

    function Uniquiness() {
      _ref = Uniquiness.__super__.constructor.apply(this, arguments);
      return _ref;
    }

    Uniquiness.extendsWithProto().concern();

    Uniquiness.ClassMethods = (function() {
      function ClassMethods() {}

      ClassMethods.prototype.validatesUniquinessOf = function() {
        throw new Error('not implemented');
        return this.validatesEachSync(arguments, function(field, options) {
          if (this[field] == null) {
            return this.errors.add(field, 'Should be present');
          }
        });
      };

      return ClassMethods;

    })();

    return Uniquiness;

  })(require('coffee_classkit').Module);

}).call(this);
